/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package petshop.panel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import petshop.util.Koneksi;
/**
 *
 * @author HP VICTUS
 */
public class LaporanKeuangan extends javax.swing.JPanel {
    private DefaultTableModel model;

    public LaporanKeuangan() {
        initComponents();
        initTable();
        loadSummaryData();
        loadRiwayatTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initTable() {
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Tipe"); // Pemasukan/Pengeluaran
        model.addColumn("Nominal");
        model.addColumn("Keterangan");
        
        tblLaporan.setModel(model);
    }
    private String formatRupiah(double nominal) {
        return NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(nominal);
    }
    
    private void loadSummaryData() {
        double totalPendapatan = 0;
        double totalPengeluaran = 0;
        
        Connection c = Koneksi.Go();
        try {
            Statement s = c.createStatement();

            // A. Hitung Pendapatan (Dari tabel 'transaksi')
            String sqlMasuk = "SELECT SUM(grand_total) AS total_masuk FROM transaksi";
            ResultSet rMasuk = s.executeQuery(sqlMasuk);
            if (rMasuk.next()) {
                totalPendapatan = rMasuk.getDouble("total_masuk");
            }
            rMasuk.close();

            // B. Hitung Pengeluaran (Dari tabel 'pembelian' - JIKA ADA)
            // Jika Anda belum punya tabel pembelian, bagian ini akan di-skip oleh try-catch jika tabel tidak ditemukan,
            // atau Anda bisa komentar dulu kodenya.
            try {
                String sqlKeluar = "SELECT SUM(total_harga) AS total_keluar FROM pembelian";
                ResultSet rKeluar = s.executeQuery(sqlKeluar);
                if (rKeluar.next()) {
                    totalPengeluaran = rKeluar.getDouble("total_keluar");
                }
                rKeluar.close();
            } catch (Exception e) {
                // Abaikan jika tabel pembelian belum ada
                System.out.println("Tabel pembelian belum ada, pengeluaran dianggap 0");
            }

            // C. Hitung Saldo
            double saldo = totalPendapatan - totalPengeluaran;

            // D. Tampilkan ke Label
            lblPendapatan.setText(formatRupiah(totalPendapatan));
            lblPengeluaran.setText(formatRupiah(totalPengeluaran));
            lblSaldo.setText(formatRupiah(saldo));
            
            // Opsional: Warna teks Saldo
            if (saldo >= 0) {
                lblSaldo.setForeground(new java.awt.Color(0, 153, 51)); // Hijau
            } else {
                lblSaldo.setForeground(java.awt.Color.RED); // Merah (Rugi)
            }
            
            s.close();
        } catch (Exception e) {
            System.err.println("Error Load Summary: " + e.getMessage());
        }
    }
    
    private void loadRiwayatTransaksi() {
        model.setRowCount(0);
        Connection c = Koneksi.Go();
        try {
            Statement s = c.createStatement();
            
            // Query mengambil data transaksi penjualan terbaru
            // Diurutkan dari tanggal terbaru (DESC)
            String sql = "SELECT * FROM transaksi ORDER BY tanggal DESC LIMIT 50";
            
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                String id = r.getString("id_transaksi");
                String tgl = r.getString("tanggal");
                double total = r.getDouble("grand_total");
                
                model.addRow(new Object[]{
                    "TRX-" + id,
                    tgl,
                    "Pemasukan", // Karena ini dari tabel transaksi penjualan
                    formatRupiah(total),
                    "Penjualan Kasir"
                });
            }
            
            // Jika Anda ingin menggabungkan dengan data pembelian (UNION), query-nya akan lebih kompleks.
            // Untuk sekarang, kita tampilkan riwayat penjualan saja dulu.
            
            r.close();
            s.close();
        } catch (Exception e) {
            System.err.println("Error Load Tabel: " + e.getMessage());
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPengeluaran = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPendapatan = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("LAPORAN KEUANGAN");

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 51), new java.awt.Color(0, 255, 102), null, new java.awt.Color(0, 255, 51)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PENGELUARAN");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 9, -1, -1));

        lblPengeluaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPengeluaran.setText("jLabel6");
        jPanel5.add(lblPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 53, -1, -1));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 255), new java.awt.Color(51, 51, 255), null, new java.awt.Color(51, 51, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PENDAPATAN");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 9, -1, -1));

        lblPendapatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPendapatan.setText("jLabel5");
        jPanel6.add(lblPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 55, -1, -1));

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 51, 0), new java.awt.Color(204, 51, 0), null, new java.awt.Color(204, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("SALDO TOKO");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 9, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSaldo.setText("jLabel7");
        jPanel7.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 54, -1, -1));

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblLaporan);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("CASH FLOW TOKO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPendapatan;
    private javax.swing.JLabel lblPengeluaran;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
